# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            emdi
tagline:          'An R package for estimating and mapping disaggregated indicators'
description:      'Here follows a short description' #'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://emdi.github.io
baseurl:          

author:
  name:           'Ann-Kristin Kreutzmann'
  url:            

gems: [jekyll-paginate]
plugins: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/soerenpannier/emdi
